name: CI Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
